version: '3.12'

services:
  db:
    image: postgres:16

    environment:
      - POSTGRES_DB=forpractic
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  web:
    build: .
    command: bash -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 DogsAndBreeds.wsgi:application"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:12345678@db:5432/forpractic
    depends_on:
      - db

volumes:
  postgres_data: