# Generated by Django 5.1.7 on 2025-03-21 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название породы')),
                ('size', models.CharField(choices=[('TN', 'Tiny'), ('SL', 'Small'), ('MD', 'Medium'), ('LG', 'Large')], max_length=6, verbose_name='Размер собаки')),
                ('friendliness', models.IntegerField(verbose_name='Дружелюбие')),
                ('trainability', models.IntegerField(verbose_name='Обучаемость')),
                ('shedding_amount', models.IntegerField()),
                ('exercise_needs', models.IntegerField(verbose_name='Необходимость в физ. нагрузках')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('friendliness__gte', 1), ('friendliness__lt', 5)), name='A friendliness value is valid between 1 and 5'), models.CheckConstraint(condition=models.Q(('trainability__gte', 1), ('trainability__lt', 5)), name='A trainability value is valid between 1 and 5'), models.CheckConstraint(condition=models.Q(('shedding_amount__gte', 1), ('shedding_amount__lt', 5)), name='A shedding_amount value is valid between 1 and 5'), models.CheckConstraint(condition=models.Q(('exercise_needs__gte', 1), ('exercise_needs__lt', 5)), name='A exercise_needs value is valid between 1 and 5')],
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя собаки')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('gender', models.CharField(choices=[('FM', 'Female'), ('ML', 'Male')], max_length=6, verbose_name='Пол собаки')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('favorite_food', models.CharField(max_length=255, verbose_name='Любимая еда')),
                ('favorite_toy', models.CharField(max_length=255, verbose_name='Любимая игрушка')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.breed')),
            ],
        ),
    ]
